---
- name: kubeadm reset
  command: kubeadm reset
  ignore_errors: True

- set_fact: join_command={{ hostvars[groups['masters'][0]]['kubeadm_join_command'] }}
  when: kubeadm_join_command is not defined

- name: join cluster
  command: "timeout .5m {{ join_command }}"
  register: result
  until: result.rc == 0
  retries: 3
  delay: 5